config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "groups#index"
  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]

    namespace :api do
      resources :messages, only: :index, defaults: { format: "json" }
    end
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :content, presence: true, unless: :image?

  mount_uploader :image, ImageUploader

  # def show_last_message
  #   if (last_message = messages.last).present?
  #     last_message.content? ? last_message.content : '画像が投稿されています'
  #   else
  #     'まだメッセージはありません。'
  #   end
  # end
end

app/controllers/api/messages_controller.rb
# class Api::MessagesController < ApplicationController
#   def index
#     @group = Group.find(params[:group_id])

#     respond_to do |format|
#       format.html
#       format.json{ @messages = Message.where("id > ? and group_id = ? ", params[:id], @group.id) }
#       binding.pry
#     end

#   end
# end

class Api::MessagesController < ApplicationController
  def index
    @group = Group.find(params[:group_id])
   
       @messages = Message.where('id > ? and group_id = ? ', params[:id], @group.id) 

    # @messages = Message.includes(:user).where('id > ?', params[:id])
    # binding.pry
  end

  # def index
  #   @messages = Message.includes(:user).where('id > ?', params[:id])
  # end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save

      respond_to do |format|
        format.html {redirect_to group_messages_path(@group), notice: 'メッセージが送信されました'}
        format.json
      end
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください'
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/views/messages/_message.html.haml
.message{data: {id: message.id}}
  .message__upper-info
    %p.message__upper-info__talker
      = message.user.name
    %p.message__upper-info__date
      = simple_time(message.created_at)
  %p.message__text
    - if message.content.present?
      = message.content
    = image_tag message.image.url, class: 'lower-message__image' if message.image.present?

app/views/messages/index.html.haml
%body
  .flash-box
  .wrapper
    .chat-side
      .side-header
        .side-header__box
          %p.side-header__box__user-name
            = current_user.name
          %ul.side-header__box__menu
            %li.side-header__box__menu__new-group
              = link_to new_group_path do
                %i.fa.fa-edit
            %li.side-header__box__menu__edit-user
              = link_to edit_user_path(current_user) do
                %i.fa.fa-cog
      .groups
        = render 'shared/group'
    .chat-main
      .main-header
        .main-header__left-box{data: { id: @group.id } }
          %h2.main-header__left-box__current-group
            = @group.name
          %ul.main-header__left-box__member-list
            %li.main-header__left-box__member-list__member
              Member :
              - @group.users.each do |user|
                %li.main-header__left-box__member-list__member #{user.name}
        = link_to edit_group_path(@group) do
          .main-header__edit-btn Edit
      .messages
        = render @messages
      .form
        = form_for [@group, @message] do |f|
          = f.text_field :content, class: 'input-box__text', placeholder: 'type a message'
          = f.label :image, class: 'input-box__image', for: 'message-image' do
            = fa_icon 'image'
            = f.file_field :image, class: 'hidden', id: 'message-image'
          = f.submit "Send", class: 'submit-btn'
        -#     %input.input-box__text#message_content{placeholder: "type a message", type: "text", name: "message[content]"}
        -#     %label.input-box__image{for: "message-image"}
        -#       %i.fa.fa-image
        -#       %input.input-box__image__file#message-image{type: "file", name: "message[image]"}
        -#   %input.submit-btn{type: "submit", name: "commit", value: "Send"}